version: '3'

services:
  app:
    build: ./nginx_node/node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./nginx_node/node:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./nginx_node/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build: ./nginx_node/nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge